# -*- coding: utf-8 -*-
"""HeatMap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ksFxkJCUIWOyfUqTC7TcelI4zSFDKJY
"""

import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
from google.colab import drive
drive.mount('/content/drive')

# Load the map image
map_image_path = '/content/drive/My Drive/AI_Recordings/Route29.png'
img = Image.open(map_image_path)
img_width, img_height = img.size

# Define the dimensions for the histogram grid
num_rows = 5
num_cols = 14

# Calculate the dimensions of each grid cell in pixels
cell_width = img_width / num_cols
cell_height = img_height / num_rows

# CSV file paths
csv_path_1 = '/content/drive/My Drive/AI_Recordings/PlayerPathTallies - BaseROM.csv'
csv_path_2 = '/content/drive/My Drive/AI_Recordings/PlayerPathTallies - CQGROM.csv'

# Load the data into the histogram grids
histogram_grid_1 = np.loadtxt(csv_path_1, delimiter=',', dtype=int)
histogram_grid_2 = np.loadtxt(csv_path_2, delimiter=',', dtype=int)

histogram_grid_1 = np.log10(histogram_grid_1)
histogram_grid_2 = np.log10(histogram_grid_2)

# Create two separate figures
fig1, ax1 = plt.subplots(figsize=(12, 6))
fig2, ax2 = plt.subplots(figsize=(12, 6))

# Display the map image on both axes
img_array = np.array(img)

# Create figures with identical settings
fig1, ax1 = plt.subplots(figsize=(12, 6), constrained_layout=True)
fig2, ax2 = plt.subplots(figsize=(12, 6), constrained_layout=True)

# Base Game Heatmap (same as before, but with fixes)
ax1.imshow(img_array)
heatmap_1 = ax1.imshow(histogram_grid_1, cmap='Blues', alpha=0.5,
                      extent=[0, img_width, img_height, 0])
cbar_1 = plt.colorbar(heatmap_1, ax=ax1, fraction=0.046, pad=0.02)
cbar_1.set_label('Player Visits (Base Game)')
ax1.set_title('Player Visit Heatmap - Base Game')
ax1.set_xlabel('X Coordinate (pixels)')
ax1.set_ylabel('Y Coordinate (pixels)')
ax1.set_aspect('equal')  # Critical for matching sizes

# Modded Game Heatmap (same adjustments)
ax2.imshow(img_array)
heatmap_2 = ax2.imshow(histogram_grid_2, cmap='Blues', alpha=0.5,
                      extent=[0, img_width, img_height, 0])
cbar_2 = plt.colorbar(heatmap_2, ax=ax2, fraction=0.046, pad=0.02)
cbar_2.set_label('Player Visits (Modded Game)')
ax2.set_title('Player Visit Heatmap - Modded Game')
ax2.set_xlabel('X Coordinate (pixels)')
ax2.set_ylabel('Y Coordinate (pixels)')
ax2.set_aspect('equal')  # Critical for matching sizes

# (Optional) Force identical axis limits
ax1.set_xlim(0, img_width)
ax1.set_ylim(img_height, 0)
ax2.set_xlim(0, img_width)
ax2.set_ylim(img_height, 0)

plt.show()